### ISSUE TITLE
3.0.6 changelog

### ISSUE THREAD

**Issue by jaimergp** [choderalab/pymbar#417]
This will be last release in the 3.x series. v4 will introduce breaking changes, so this micro release will add deprecation warnings and some bugfixes. List so far:

- [X] Add deprecation warnings for new PEP8-compliant names -- see #368
- [X] Add future warnings for the behavior of `return_dict=True` -- see #414
- [ ] Add deprecation warnings for `old_mbar`  
- [X] Backport tests and fixes from #350 -- see #414

**Comment by xiki-tempula** [comment]
Is it possible to have 3.0.6 in pip, please? Thank you.

**Comment by jaimergp** [comment]
@mikemhenry - this issue is outdated I guess. Can you take over? Thanks!
